# Generated by Django 5.0.7 on 2024-07-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipe_name', models.CharField(max_length=100)),
                ('Receipe_discription', models.TextField()),
                ('Receipe_images', models.ImageField(upload_to='receipe_image')),
            ],
        ),
    ]
