# Generated by Django 5.0.7 on 2024-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='Receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
